### ISSUE TITLE
deprecated async_get_registry method import for HA 2023-05

### ISSUE THREAD

**Issue by Doubledom45** [crazymikefra/HA_RFPlayer#17]
Suite mise à jour HA 2023-5

 ### Unable to import component: cannot import name 'async_get_registry'
Modification du `_init_.py`
```
27   from homeassistant.helpers.device_registry import async_get_registry
```
**from homeassistant.helpers import device_registry as dr**
```
640           device_registry = await async_get_registry(self.hass)
```
**device_registry = dr.async_get(hass)**

**Comment by Doubledom45** [comment]
Je ne fais pas un **Pull Requests** car je ne sais pas ou tu en es de tes modifications !

**Comment by prahal** [comment]
Pull request fait indépendamment #18
